### ISSUE TITLE
Update WinRM dependent gem 'logging', '~> 1.6', '>= 1.6.1' to latest i.e ~> '2.0'

### ISSUE THREAD

**Issue by siddheshwar-more** [WinRb/WinRM#147]
@sneal  @mwrock @ksubrama @pmorton @zenchild 

Currently  WinRM `'logging', '~> 1.6', '>= 1.6.1'`  gem refer-  https://github.com/WinRb/WinRM/blob/master/winrm.gemspec#L34  conflicts with latest logging gem used in `knife-google's` dependent gem [googleauth.gemspe](https://github.com/google/google-auth-library-ruby/blob/master/googleauth.gemspec#L29) 

This creating problem for `knife-google` + `chef-dk` combo. Please refer- https://github.com/chef/knife-google/issues/65 

Is there any particular reason we locked  `'logging', '~> 1.6', '>= 1.6.1'` for `winrm` ? If not then we should update this dependency with latest one. 

Thank you!

**Comment by sneal** [comment]
I assume the logging gem is following [semver](http://semver.org/) which means we can be pretty confident that the winrm gem will work with every 1.x release of logging. However, 2.x logging is another story. Its possible that winrm _may_ work with logging 2.x without any changes, but its also likely not too since 2.x implies they made backwards incompatible changes. I don't know.

Depending on whether winrm works without any additional changes will dictate the potential solution for this. Hopefully we only need to change the constraint to: `s.add_runtime_dependency 'logging', ['>= 1.6.1', '< 3.0']`

**Comment by siddheshwar-more** [comment]
@sneal 
Yeah, I think we have to just change `s.add_runtime_dependency 'logging', ['>= 1.6.1', '< 3.0']` 

Lets us know If you need any help to verify WinRM logging dependency after updating it to 2.x .

**Comment by sneal** [comment]
Fixed by #148
