### ISSUE TITLE
powershell does not have exit status for chef-solo in kitchen

### ISSUE THREAD

**Issue by b-dean** [WinRb/WinRM#229]
The basic problem is that I have a cookbook with minitest tests that run in a chef handler and on Windows they aren't causing `kitchen` to return a non-zero exit status even though if I run the same `chef-solo` command logged into the VM, I get an exit status of 1.

The repo [b-dean/winrm-issue-229](https://github.com/b-dean/winrm-issue-229) has an example cookbook that shows this behavior. Its `README.md` explains how to reproduce the bug.

This could be a problem with test-kitchen but I'm pretty sure it's something in winrm based on my digging around in the gem. The `WinRM::PSRP::ReceiveResponseReader#find_exit_code` method never gets a message that has the exit code. The powershell command that kitchen sent is:

```powershell
$env:TEST_KITCHEN = "1"
$env:PATH = try { [System.Environment]::GetEnvironmentVariable("PATH","Machine") } catch {}

& $env:systemdrive\opscode\chef\bin\chef-solo.bat --config $env:TEMP\kitchen\solo.rb --log_level auto --no-color --json-attributes $env:TEMP\kitchen\dna.json  --force-formatter
```
I don't understand what changed between winrm 1.x and 2.x that it's no longer seeing an exit status, but it's not. That's what makes me think it's a winrm bug, not a kitchen bug.

It's maybe worth noting that when I use the [winrm-elevated](https://github.com/WinRb/winrm-elevated) gem and the same cookbook, kitchen does exit with a non-zero exit status, but it isn't the `20` which means an unexpected failure, as opposed to the `10` I would expect from a failed chef-client run (older test-kitchen versions `< 1.8` exited with a `10`). *That* seems like it might be a kitchen bug.

**Comment by mwrock** [comment]
Thanks for this issue!

I am able to reproduce the problem. Winrm v2 handles exitcodes from powershell fundamentally differently from previous versions. The WSMV protocol used in v 1.x would send an exitcode in the SOAP response of the command. The PSRP includes the same data in the SOAP but it is always 0 because it is not expected to be used (and we don't). Rather, PSRP handles exit codes from specific powershell pipeline messages. If a command calls `exit 1` then we get a `PipelineHostCall` message with a `SetShouldExit` of `1`. However if a command line executable emits an exit code, that is handled in a fundamentally different way. A powershell routine would call `$LASTEXITCODE` and the code returned would match the code returned by the failed executable.

So we need to append commands with a check to `$LASTEXITCODE` and then specifically call `Exit` with the returned code so that we intercept the command and the WinRM:Output gets the correct exitcode.

I'm going to make this a high priority to fix.

**Comment by mwrock** [comment]
Another thought is to leave it to clients to deal with this and call `$LASTEXITCODE` but I'm leaning toward the original idea above.

**Comment by mwrock** [comment]
I think 2.0.3 fixes this at the winrm level. I tested with your cookbook and TK returns a `20` which seems wrong but looks like an issue with TK and should be addressed there.

**Comment by b-dean** [comment]
Thanks @mwrock!
