### ISSUE TITLE
Multi-Hop feaure

### ISSUE THREAD

**Issue by jcalonsoh** [WinRb/WinRM#275]
if possible to add multihop feature for the alternative ssh-gateway ?

https://msdn.microsoft.com/en-us/library/ee309365(v=vs.85).aspx

**Comment by mwrock** [comment]
Its really not a limitation of that gem so much but a limitation of the authentication method. There would need to be a ruby implementation of CredSSP. Similar to the ruby NTLM gem. However, often winrm-elevated can workaround the multihop issue because it runs everything through a local scheduled task and is therefore not subject to remote account limitations.
